### ISSUE TITLE
error when "python tofreezelite.py"

### ISSUE THREAD

**Issue by bigcash** [tinoucas/spleeter-tflite-convert#1]
WARNING:tensorflow:From tofreezelite.py:6: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Traceback (most recent call last):
  File "tofreezelite.py", line 6, in <module>
    model = tf.compat.v1.saved_model.load(savedModelDir)
  File "/home/lingbao/soft/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
TypeError: load() missing 2 required positional arguments: 'tags' and 'export_dir'

miss two params: session and tags
how to fix it?
thanks!

**Comment by sugartarou** [comment]
maybe, you are using tensorflow 1.x.

I reproduced same error in tensorflow 1.15.2 and 1.14.0.
And I successed to execute tofreezelite.py in tensorflow 2.5.0.
